version: "3.3"
services:

  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  rancher:
    image: rancher/rancher
    container_name: "rancher"
    user: root
    privileged: true
    deploy:
      replicas: 1
      restart_policy:
        condition: unless-stopped
    volumes:
      - "/opt/volumes/rancher:/var/lib/rancher"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rancher.rule=PathPrefix(`/{path:.*}`)"
      - "traefik.http.routers.rancher.entrypoints=web"
      - "traefik.http.services.hello.loadbalancer.server.port=80"
