version: "3.3"
services:

  traefik:
    image: "traefik:v2.2"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  hello:
    image: nginxdemos/hello
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.hello.rule=PathPrefix(``)" # Equivalent to a wildcard for everything
        - "traefik.http.routers.hello.entrypoints=web"
        - "traefik.http.services.hello.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
